### ISSUE TITLE
Maison logiciel libre est mal écrit dans le titre des pages

### ISSUE THREAD

**Issue by RignonNoel** [MaisonLogicielLibre/Website#1014]
1- il faut supprimer les majuscule à 'logiciel' et à 'libre'

2- écrire le nom du site est une mauvaise pratique d'interface. Il faudrait écrire quelque chose de plus descriptif de l'endroit où l'on es (missions, projets, profil, accueil)

**Comment by fxleblanc** [comment]
Ok pour le titre. Pour le point 2, je transfère à #1015
