### ISSUE TITLE
Impossible d'enregistrer le profil

### ISSUE THREAD

**Issue by sbstp** [MaisonLogicielLibre/Website#1024]
Quand j'essaie de mettre à jour mon profil, je reçoit le message d'erreur suivant: `L'utilisateur n'a pas pu être enregistré. Veuillez réessayer.` Réessayer ne fonctionne pas.

Ma page de profil: https://maisonlogiciellibre.org/users/view/91
Browser: Firefox/Iceweasel 44.0.2 / Chromium 48 sur Debian stretch,

**Comment by fxleblanc** [comment]
@sbstp quels champs as-tu modifié dans ton profile? Cette erreur est produite lorsque les données modifiées ne sont pas en accord avec les règles de validation du modèle.

**Comment by sbstp** [comment]
J'ai essayé de changer mes intérêts.
