### ISSUE TITLE
Menu utilisateur indisponible sous smartphone

### ISSUE THREAD

**Issue by RignonNoel** [MaisonLogicielLibre/Website#1027]
Lorsque nous sommes sur mobile et que nous voulons nous rendre sur notre profil il faut faire plusieurs étapes.

- ouvrir le menu
- ouvrir le sous menu utilisateur
- cliquer sur 'mon profil'

Hors lorsque le menu est ouvert, le sous menu utilisateur devient indisponible. 

Je pense que ce dernier passe sous le menu de base qui est rendu statique en haut de page.

**Comment by fxleblanc** [comment]
Je vais régler le problème en hotfix mais il faudrait épurer la version mobile. Voir #1028

**Comment by fxleblanc** [comment]
@RignonNoel, le fix est disponible sur test.maisonlogiciellibre.org/site
