### ISSUE TITLE
FACIL n'est pas commanditaire

### ISSUE THREAD

**Issue by mathieugp** [MaisonLogicielLibre/Website#1075]
FACIL apparaît toujours comme commanditaire (aux côtés de Savoir-faire Linux et de la Ville de Montréal) sur la page d'accueil de maisonlogiciellibre.org

Il s'agit d'une erreur : FACIL n'est que partenaire associatif, comme .Cie, Cedille, ApplETS et Conjure.

(Communiquez avec Ted Hill si vous avez besoin d'une confirmation.)

**Comment by fxleblanc** [comment]
Bien sûr, désolé de l'erreur.

**Comment by mathieugp** [comment]
Merci! :-)
