### ISSUE TITLE
COMPÉTENCES in my profile as anonymous user

### ISSUE THREAD

**Issue by appliedrd** [MaisonLogicielLibre/Website#1090]
Only students can edit COMPÉTENCES. So for others, we should supress this field from their profile.

**Comment by willkoua** [comment]
Les autres sont les professeurs et les mentors??

**Comment by willkoua** [comment]
D’après la BD, on peut être à la fois étudiants, professeurs et mentor. Est-ce possible?
Si oui, quelles doivent être les conditions précises pour ne pas avoir accès à la fonctionnalités compétence
Si non, il faudra modifier la base de données

**Comment by willkoua** [comment]
@appliedrd  qui sont les autres ??

**Comment by appliedrd** [comment]
already done
