### ISSUE TITLE
Ajouter des informations pour faciliter la validation des organisations 

### ISSUE THREAD

**Issue by willkoua** [MaisonLogicielLibre/Website#1180]
Actuellement dans la page d'accueil de l’administration, on ne peut pas savoir quant est ce que une organisation a été créée. Parmi les informations qu'on pourraient choisir il y a:
- l'ajout de la date de création 
- un tag qui permettrait de savoir si oui ou non il y a des missions

**Comment by willkoua** [comment]
@fxleblanc est ce que une organisation qui n'a pas de projet peut etre valide??

**Comment by fxleblanc** [comment]
Non. Fait attention par contre, des fois les organisations et les projets sont crées sans être liées. Il faut donc que tu fasses une petite enquête pour savoir si le projet peut potentiellement être lié à une organisation.
