### ISSUE TITLE
Feedback for main page

### ISSUE THREAD

**Issue by fuhrmanator** [MaisonLogicielLibre/Website#1199]
Here's some feedback about the current site's usability:

- [x] The carousel is nice, but none of the images are clickable. For example, when I see "Nouvelle Chaîne Youtube" I want to click on that image to go to the Youtube channel! Same is true for all the other images. Make them clickable.
- [x] There are hovers for the Étudiant and Industriel icons on the main page, but when I click there is nothing. I find this very misleading. Why can't my clicks there go some place? For Industriel, it says "Proposer un projet...", so a click on that should take me to a place where I can do that, right? The same thing would make sense for the Étudiant. Perhaps you can consider a portal for each type of user?
- [x] The "commanditaires" icons don't have links to go anywhere, but the "partenaires" do. This seems inconsistent to me. 
- [x] The section "Embaucher des stagiaires, diplômés et PFE" also has no links to take people anywhere. Perhaps it should advise industry/profs to "create a mission or project" and take them to that part of the site, etc.
- [x] Resizing the window in Chrome on Windows 10 causes the carousel/image to break. I see this error in the console `Failed to load resource: the server responded with a status of 404 (Not Found) 
https://maisonlogiciellibre.org/img/carousel/1-mobile.jpg`

Here's the screen shot that several items refer to:

![image](https://cloud.githubusercontent.com/assets/7606540/15799470/b2f8092c-2a2b-11e6-8479-7c4949c00137.png)

**Comment by willkoua** [comment]
@fuhrmanator pour ton point sur le faite de rendre les images du carrousel cliquables je suis pas très d'accord car, rendre l'image du youtube cliquable serait pertinent mais pas vraiment les autres. Donc, moi je propose de mettre un logo YouTube qui mènera vers la page en question

**Comment by willkoua** [comment]
à propos du 3e point, cette [issue (issue 1201](https://github.com/MaisonLogicielLibre/Website/issues/1201) devrait le résoudre

**Comment by fuhrmanator** [comment]
@willkoua Voici les liens que je voyais pertinents dans le carousel:

- Chaîne Youtube
- un lien vers l'atelier C/C++ (Google m'a trouvé ceci: https://interfaceets.wordpress.com/2016/05/13/edition-speciale-atelier-cc-avec-mozilla/)
- Pour le support de 25k$ de la ville de MTL Google m'a trouvé http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&_dad=portal&_schema=PORTAL&id=26523

**Comment by willkoua** [comment]
encore d'accord avec les liens que tu viens d'envoyer. Mais, on a d'autres images dans le carrousel (une image sur les partenaires ou alors une image du bureau de ML2) qui ne peuvent avoir de lien. À la fin, on se retrouvera avec des images cliquables et d'autre pas (ce qui pourrait être perturbant).  Mais, le point que tu soulève est pertinent au moins pour les événements donc, je propose de mettre un bouton sur les images des événements qui amèneront à leur lien

**Comment by fuhrmanator** [comment]
@willkoua Point 5 seems still open. The front page I see says (with no concrete actions):

> Embaucher des stagiaires, diplômés et PFE
Industrie et gouvernement : Développez des fonctionnalités, des outils et des librairies open source dans vos produits. Faites la promotion de votre entreprise dans notre communauté open source

> Professeurs universitaires : Allégez la charge de travail de l'affichage, de la recherche de projets et du suivi des progrès de l'élève. Tirez parti de nos auxiliaires d'enseignement et de notre infrastructure.

**Comment by willkoua** [comment]
je suis d'accord avec le point 1 mais, je ne pense pas que ce serait une bonne idée de rendre certaines images du carrousel cliquables car, toutes ne peuvent pas l’être (image sur les partenaires, image du bureau de ML2) et on se retrouverait avec des images cliquables et d'autre pas. Ce que je propose, c'est de mettre un bouton sur l'image qu'on veut cliquable pour que l'utilisateur puisse voir du premier coup d’œil qu'il peut cliquer dessus.
