### ISSUE TITLE
Navigation bar wrap over page content on narrow windows.

### ISSUE THREAD

**Issue by sebmarchand** [MaisonLogicielLibre/Website#228]
See attached image, the navigation bar wrap over the page content:

![image](https://cloud.githubusercontent.com/assets/245780/10488978/30d634a2-7269-11e5-848a-f1c8f75276dc.png)

**Comment by RignonNoel** [comment]
Yes, it's true. The problem is already know but not fix for the moment.

Thx!

**Comment by RignonNoel** [comment]
After research the problem is a normal working of bootstrap. It's not very beautiful but for the moment it works.

A refont of navigation tools is plain. Just wait !

Thanks.
