### ISSUE TITLE
Problem of convention PEAR/Cakephp on switch

### ISSUE THREAD

**Issue by RignonNoel** [MaisonLogicielLibre/Website#259]
Cakephp want an indentation
Pear doesn't like this!

Find how remove switch from pear.

**Comment by RaphaelStArnaud** [comment]
The best solution would be to make our own standard with the best of both world but it is quite lengthy to do so

**Comment by fxleblanc** [comment]
@RignonNoel is this issue still relevant. The current configuration doesn't seem to suffer this issue.
