### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 La table 'mll_site.organizations_owners' n'existe pas

### ISSUE THREAD

**Issue by appliedrd** [MaisonLogicielLibre/Website#299]
![organization](https://cloud.githubusercontent.com/assets/5149368/10727030/1fb0da86-7bad-11e5-9c60-c76c73f14a40.png)

**Comment by appliedrd** [comment]
this is when you list organizations

**Comment by RignonNoel** [comment]
You need to migrate your db.

bin/cake migrations migrate

After, dont forget to populate db with populate.SQL file
