### ISSUE TITLE
more explicit mission statement

### ISSUE THREAD

**Issue by appliedrd** [MaisonLogicielLibre/Website#306]
change this to something more explicit

After submit the project, you will be redirect on the project's page to create some missions.

**Comment by appliedrd** [comment]
make this more clear

You're not part of an organization. Add yours now!

**Comment by RignonNoel** [comment]
@appliedrd : Have you worked on ?
 
We launch the next release tomorrow, so we need the texts or otherwise it will be in an other release (next week)

**Comment by appliedrd** [comment]
next release
