### ISSUE TITLE
problem space

### ISSUE THREAD

**Issue by RignonNoel** [MaisonLogicielLibre/Website#319]
- space in gravatar message:
  - Cet avatar est un gravatar liée avec votre email . Si vous voulez changer votre avatar , allez surgravatar.com

- space in submit project:
  - Ou vous pouvez ajouter de nouvelles organisationsici.

**Comment by jenwei** [comment]
@RignonNoel - I'd be happy to help with this! Is this just cleaning up the text (i.e. the extra space between the two sentences of the first bullet point)?

**Comment by RignonNoel** [comment]
Hi @jenwei, i've no problem with that!

Just delete space in source code between PHP tag and verify translation files.

**Comment by RignonNoel** [comment]
Just for the gravatar, the file is "src/Template/Cell/Sidebar/user.ctp" and not "user/view.ctp"

**Comment by jenwei** [comment]
Hmm. I found the english version of the first message, but it doesn't seem to have the spacing issue, and I searched the repo for the second one ('space in submit project') and didn't see an issue there either :confused:

**Comment by RignonNoel** [comment]
Here it's the line for the gravatar issue :

` <p><?= __('This avatar is a gravatar linked with your email. If you want change your avatar, go on '); ?><a href="http://gravatar.com/">gravatar.com</a></p>`

As you can see, we don't have any space between the end of the PHP tag and the begin of the HTML element (a), but we have a space at the end of the string who as translated by PHP. It's bad..

You just need to delete the space in the string, add a space between the two tags and update translation file in fr_CA to make changement (take care to have no one space at the end of the line in the translation file, for this you can use [poEdit](http://poedit.net/) )

The second problem seem to be corrected by an other PR.

**Comment by RignonNoel** [comment]
@jenwei :

Always on the task or i move it back in Ready?

I just to know because we launch the next release tomorrow.

**Comment by jenwei** [comment]
@RignonNoel - sorry! haven't gotten to it yet, so I don't think I'll make it for the next release.

**Comment by RignonNoel** [comment]
@jenwei: No problem i move your task in a futur release
Take us inform! ;)
