### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by appliedrd** [MaisonLogicielLibre/Website#350]
I logged in and got this screen:

![login-error](https://cloud.githubusercontent.com/assets/5149368/10909978/85850540-820a-11e5-8dfb-86ee6709931a.png)

**Comment by RignonNoel** [comment]
Yes, it's a bug.

When you go directly on the login page without use the home page the login method bug.

You need to have a provenance because the login method redirect you to your provenance after the connection.

For the moment, just doesn't use directly the login page. Pass by the home page.
