### ISSUE TITLE
Implement markdown on textarea

### ISSUE THREAD

**Issue by appliedrd** [MaisonLogicielLibre/Website#352]
preserve the carriage - control linefeed of the project and mission descriptions and competencies. when I submit, everything got mushed together

**Comment by RignonNoel** [comment]
We are already on the functionnality. It's not a bug but just an enhancement.

A complete system of markdown would be implemented tomorrow.

The markdown system suport (not exhaustive):

 - List
 - Bold
 - Link
 - Heading
 - Quote
 - Code
 - Italic
