### ISSUE TITLE
Linux Penguin copyright

### ISSUE THREAD

**Issue by appliedrd** [MaisonLogicielLibre/Website#427]
acknowledge the GIMP. see here: 
http://isc.tamu.edu/~lewing/linux/

**Comment by RignonNoel** [comment]
> Permission to use and/or modify this image is granted provided you acknowledge me lewing@isc.tamu.edu and The GIMP if someone asks.

**If someone asks** : So we don't need to add an acknowledge, just recognize the work of gimp if someone asks.
