### ISSUE TITLE
change list paging from 10 to 50 (paginate)

### ISSUE THREAD

**Issue by appliedrd** [MaisonLogicielLibre/Website#461]
set default to 50 instead of 10

**Comment by simon-begin** [comment]
For all datatables or only for projects ?

**Comment by RignonNoel** [comment]
I think we should do it for all indexes.

**Comment by simon-begin** [comment]
- For non-index pages, put 25
- Put 50 for my projects and my organizations

**Comment by RignonNoel** [comment]
I've put to 50 projects and organizations in PR #462
