### ISSUE TITLE
Remake design in dashboard

### ISSUE THREAD

**Issue by simon-begin** [MaisonLogicielLibre/Website#486]
Make the MLL style more dashboard like

- [x] Users
  - [x] Delete 
  - [x] Edit
  - [x] Email
  - [x] Index
  - [x] View
  - [x] Password
  - [x] Login
  - [x] Recover
  - [x] Reset
  - [x] Register
- [x] Projects
  - [x] index 
  - [ ] index_admin 
  - [x] apply
  - [x] edit 
  - [x] edit_mentor 
  - [ ] my_projects 
  - [x] submit 
  - [x] view

**Comment by simon-begin** [comment]
Something I will make off-hour

**Comment by simon-begin** [comment]
![Dashboard](http://i.imgur.com/xF8U84x.png)

**Comment by simon-begin** [comment]
![Login](http://i.imgur.com/AuKBbSf.png)
![Register](http://i.imgur.com/2f6KxTW.png)

**Comment by RaphaelStArnaud** [comment]
:crown:

**Comment by RignonNoel** [comment]
:pear:

**Comment by simon-begin** [comment]
![Profile](https://i.imgur.com/TaoHscP.jpg)

**Comment by RignonNoel** [comment]
Joli! Par contre ça pose la question de limité la taille de la biographie si elle ce retrouve en haut de page. 
Moi j'ai eu quelques imprévu ce week-end. Mais je vais m'y mettre activement cette nuit et demain 6H30.

**Comment by simon-begin** [comment]
la bio a un min-height: 100px; donc si tu as seulement une ligne c'est pas aussi gros

**Comment by simon-begin** [comment]
On pourra peut-être mettre une limite de char

**Comment by simon-begin** [comment]
Plus un petit effet complètement inutile... quand tu passes ta souris sur le bloc où l'avatar est... ça fade vers le vert
![Profile hover](http://i.imgur.com/Mwwb633.jpg)

**Comment by RignonNoel** [comment]
YEAHHH!! xD

**Comment by simon-begin** [comment]
User->edit, password, email et index en cours

**Comment by simon-begin** [comment]
Je viens de merge la develop sur la branche, donc nous avons tous les plus récents changements

**Comment by RignonNoel** [comment]
Je me lance pour organizations

**Comment by simon-begin** [comment]
Ok, j'ai presque fini la page du projet. J'ai ajouté un générateur d'avatar

**Comment by RignonNoel** [comment]
Bien ça =)
Le temps que je prépare le repo en local, puis dès que tu push je commence la copie pour organization. Puisque de toute façon ça se ressemble pas mal

**Comment by simon-begin** [comment]
Je devrais avoir fini dans 15-20min max

**Comment by RignonNoel** [comment]
Je ne sais pas si c'est dans le merge, mais tu a perdu le message d'info en haut de projet

**Comment by simon-begin** [comment]
Dans l'index du projet ? Je vais le remettre.

**Comment by RignonNoel** [comment]
Oui dans index.

**Comment by RignonNoel** [comment]
default.ctp -> line 88 :
Le lien vers myOrganizations contient un espace qu'il faut supprimer.

my Organizations -> myOrganizations

**Comment by simon-begin** [comment]
Ok
!(Projects)[http://i.imgur.com/ax9i21a.png]

**Comment by RignonNoel** [comment]
Sympa! ça a de l'allure!

**Comment by simon-begin** [comment]
J'ai fait les 2 petits fix

**Comment by RignonNoel** [comment]
Le helper pour "Organisations" sur projet view pointe dans le vent (le point d'interrogation vers le wiki)
