### ISSUE TITLE
System of message/alert on page

### ISSUE THREAD

**Issue by RignonNoel** [MaisonLogicielLibre/Website#498]
Add a system of message/alert on page.

We want an admin form where we can add a message, a type (warning, error, info) and a page and save it in the DB.

The message/alert is display on the top of each page. (layout.html)

**Comment by RignonNoel** [comment]
Wait refont of the design. For the moment it's useless and the architecture need to be changed.

**Comment by fxleblanc** [comment]
Activity history by organizations
