### ISSUE TITLE
Copy, spelling and translation issues

### ISSUE THREAD

**Issue by nicbou** [MaisonLogicielLibre/Website#511]
Hi there! Pardon the nitpicking, but there are several errors in the original copy and its French translation. Since you are trying to establish credibility in the field, these details are fairly important.

I've only seen 20% of the strings, but here's what I have so far:

Objectively wrong
---------

* "Candidater" [is not a word](http://www.academie-francaise.fr/candidater). Watch for other variations (e.g. candidaté) in the .po file.
* "Modifier" and "Éditer" are both valid, but you should stick to one for consistency.
* "Please try again", "Please, try again" and "Please,try again". The first version is the commonly used one, and the last one is a typo.
* "SVN" is an abbreviation, not a word. It should be capitalized in both languages. Also, it's "the SVN repository", not "the svn"
* "Le rôle a étéenregistré." is missing a space.
* "Nom d'utilisateur ou mot de passe inccorect, veuillez réessayer". The correct spelling is "incorrect", and "Veuillez réessayer" should be a separate sentence for consistency.
* "You have applied on the mission". You apply *for* a mission. There are several variations of this one.
* "Error in sending email, please try again" should be "An error occurred while sending the email. Please try again."
* "Vous devez sélectionner au moins un choix." should be "Vous devez sélectionner au moins une option". On sélectionne une option et on fait un choix.

Subjectively wrong
---------

* "Accepter" and "Approuver" are both valid, but you should stick to one for consistency.
* The translation of "updated" is "mis à jour", not "modifié".
* "No account associated with this information, try again". Why would trying again change anything? The translation even assumes that the account might exist, but that we can't find it: "Nous n'avons pas pu trouver votre compte. Veuillez réessayer". "No matching account found" should do the trick.
* "Is not a valid number." and its translation are inconsistent with the surrounding error messages. It should be "This number is not valid" or "This value is not a valid number" depending on context.
* "Old password isn't valid" should be "The old password is incorrect".
* "Project's page". "Project page" is more commonly used. Same for "Organisation page"
* "Add/edit [object]" vs "Add/edit an/the [object]". Pick one format and stick to it.
* "List of projects" should be "Project list"
* "Add an projects" should be "Add a project"
* "New Comment": [Do not use Title Case for buttons.](http://ux.stackexchange.com/questions/28297/should-we-use-title-case-or-sentence-case-for-headlines-and-buttons)
* "Notre mission est d'améliorer les compétences de développement et le potentiel d'embauche des étudiants universitaires en logiciel par le biais d'expérience pratique sur des projets de logiciels libres et d'open source". This is why people hate academics. Write for your readers and tell it like it is: "We help computer science students sharpen their practical skills by working on open source software". "Nous aidons des étudiants en génie logiciel à obtenir de l'expérience pratique en travaillant sur des projets open source".

**Comment by nicbou** [comment]
As a side note, never divide translation strings. Not every sentence follows the same structure in both languages. The home page copy is a perfect example of that:

"S'enregistrer pour rejoindre notre communauté grandissante de professeurs et d'étudiants universitaire, de partenaires industriels et d'associations du Québec."

By the way, there's a grammar mistake in there too. "Étudiants universitaire**s**".

**Comment by RignonNoel** [comment]
Thanks for your return.

We already know that there are many errors in our translation. But your help is welcome, and your details will save us lot of time.

We already start to make a refactoring of our code, to replace all divide translation string, but it take lot of time and we have many other priorities. So for the moment we just doesn't add new divided translation strings.

For the rest:

 - Lot of lines are generates by CakePhp and we doesn't have time for the moment to change defaults string
 - I will send your suggestion of mission to the person in charge
 - Many of your suggestions require further discussion, but if you have time you can work on or come to our office.

**Comment by nicbou** [comment]
(pardonne mon anglais! j'ai vu que la langue originale du site était l'anglais)

Je ne vais plus à l'ÉTS, donc je ne pourrai pas passer à votre bureau. J'ai simplement reçu un courriel de Jean-Marc Robert ce matin, et j'aime bien l'initiative.

À vous d'en faire ce que vous voulez (ou pouvez; vous êtes en fin de session bientôt).

**Comment by RignonNoel** [comment]
Étudiant ou non, toute contribution est la bienvenue.
Dans tout les cas, merci.
