### ISSUE TITLE
Flags when choosing language are a bad practice

### ISSUE THREAD

**Issue by fuhrmanator** [MaisonLogicielLibre/Website#613]
When I see the current language menu:

![image](https://cloud.githubusercontent.com/assets/7606540/11564872/7481d262-99a9-11e5-939f-5c65c2747362.png)

I get the impression that in Quebec one only speaks French and in Canada one only speaks English. Flags are a bad practice according to UX experts, because they rarely signify one language.
 
http://ux.stackexchange.com/questions/11891/should-i-use-country-flags-in-language-selection-fields

The best practice seems to be to put the language only in its own language, e.g., Français / English

Have a look at this answer for more discussion of advantages/disadvantages: http://ux.stackexchange.com/a/2515/47461

**Comment by RignonNoel** [comment]
Issue has been accepted. I've make the enhancement.
It will be in production soon.
