### ISSUE TITLE
Implement new information on profile page

### ISSUE THREAD

**Issue by RignonNoel** [MaisonLogicielLibre/Website#624]
We want some information on user :

 - New textarea for interest
 - Email public
  - Set email on email public
 - Réseaux sociaux
  - Facebook
  - Twitter
  - Google+
  - Linkedin
 - Prefered language
 - Interest

**Comment by RaphaelStArnaud** [comment]
20151204143507_add_interest_to_users.php
       
$table->addColumn('interest', 'textarea', [  ->  $table->addColumn('interest', 'text', [

**Comment by RaphaelStArnaud** [comment]
Update text to be in the same format as the rest of the profile. Better integration =)

**Comment by RaphaelStArnaud** [comment]
It feels weird to have to input the full link for twitter, facebook, etc. Maybe only make so the user only have to input the username when possible.

**Comment by RaphaelStArnaud** [comment]
Public email does not show after it is filled out on modify profile

**Comment by RignonNoel** [comment]
- [x] textarea -> text
- [x] Same format of title -> refactoring css
- [x] twitter, facebook as username, all rest as URL
- [x] public email debug
