### ISSUE TITLE
User stories for Professors seeking capstone, Student seeking capstone

### ISSUE THREAD

**Issue by fuhrmanator** [MaisonLogicielLibre/Website#652]
It would be good to consider user stories for a professor seeking capstone and Student seeking capstone. 

> As a professor, I want to find open source projects that I can propose to my senior students who are enrolled in the capstone project and need a good subject, because it's part of my responsibility to help them find good projects.

I thought of supporting that user story with subscription to emails. 

> As a professor, I want to know about open source projects that are proposed as capstone projects but are in need of a professor to supervise them, because it's my responsibility to supervise capstone projects.

There's also a use-case point of view: 

![Use cases for capstone projects](http://www.plantuml.com/plantuml/svg/TL2nJiGm3Dtz5HvXE0R6JYSXtGGIKiNM9MtSNg1rAjjH1yI_uzprW8LCiT_pU_OxgWMniimmqsXe6ILDPyEOX0PBcS6IpOHlIlWKb1J7BFZo_0XG2O4d1qyKh8XZdu3-xaw9OyT3MDKoKyUhv7Sdwpq6dn_MAwijlGwIUYUuROWnLR-EyuZ_Z6hfuGkWQQr4OckWUPKyacgM1c3luk5YyOFizIzQLVwYjGREHllfxbzRBN5Kf2MakSPIbCGpCaiyePrfmG_E6mPask2sB-xhuXOK_2AA3-0oMDK1ZlxrfBy1)

I considered students having the same needs, although it's not my role anymore :-)

**Comment by fxleblanc** [comment]
The discussion has been transfered to #791. Closing

**Comment by fuhrmanator** [comment]
Felix, wouldn't it be better to transfer #791 to here? Sorry for the duplication.

**Comment by fxleblanc** [comment]
The way I see it is that the model you are proposing in this is what gave us(me and Noel) in part the inspiration for #791, which is why I transfered the discussion/design/implementation in #791 as an evolution to your idea/issue here.
