### ISSUE TITLE
refactor index of project and organization

### ISSUE THREAD

**Issue by RignonNoel** [MaisonLogicielLibre/Website#665]
Project
 - Number of mission with place available
 - Type of mission available
 - Remove link
 
Organization
 - Number of mission with place available
 - Type of mission available
 - Remove link

**Comment by simon-begin** [comment]
Need to do #675 before

**Comment by RignonNoel** [comment]
Missions

 - Add number of place by type
 - Add number of all application (only for admin)
 - Add number of all application accepted (only for admin)

**Comment by RignonNoel** [comment]
Wait January for a big refactor. I close this issue
