### ISSUE TITLE
mission tagging

### ISSUE THREAD

**Issue by appliedrd** [MaisonLogicielLibre/Website#691]
Uni- or Prof-specific tags that a prof could place on a project, e.g., ETS-capstone (Jean-Marc would scan and approve as a recommendation for his department) or ETS-Fuhrman-Capstone (individual prof vetting). Not sure if tags are the way to go, but it's a way to say, "bid" on a project

**Comment by RaphaelStArnaud** [comment]
Something similar as been done in ticket 664
