### ISSUE TITLE
500 partout

### ISSUE THREAD

**Issue by aviau** [MaisonLogicielLibre/Website#702]
Salut,

J'ai des 500 à chaque fois que je veux visualiser une entité:
 - projet
 - organisation
 - mission

Ca devrait être facile à reproduire, cliquez n'importe-ou!

![screenshot from 2015-12-11 14-51-20](https://cloud.githubusercontent.com/assets/2706882/11754019/ab4b9ad0-a016-11e5-9404-3b656ef1f274.png)

**Comment by RignonNoel** [comment]
L'erreur est normale, nous étions en train de mettre en place la dernière version de la plateforme.

Nous nous excusons de la gène occasionné.
