### ISSUE TITLE
Déplacer une mission dans une org

### ISSUE THREAD

**Issue by aviau** [MaisonLogicielLibre/Website#705]
Vous allez finir par me créer un tag support :)

Salut,

J'ai récament découvert que mes missions n'étaient pas dans une organisation, alors je les ai re-crées dans une org.

Parcontre, j'en ai une que je ne peux pas archiver et re-créer parce que j'ai déjà accepter des candidats.

Pouvez vous déplacer cette mission:
 - https://maisonlogiciellibre.org/missions/view/23

Dans ce projet:
 - https://maisonlogiciellibre.org/projects/view/31

Et dans cette org:
 - https://maisonlogiciellibre.org/organizations/view/18

Ensuite, on pourra supprimer ce projet:
 - https://maisonlogiciellibre.org/projects/view/25

**Comment by RignonNoel** [comment]
Pour faire passer un projet vers une organisation il suffit de créer ton organisation et d'éditer ton projet pour l'associer à cette nouvelle organisation.

Cependant GitHub n'est pas le bon endroit pour faire ce genre de ticket, a l'avenir prévilégie notre adresse mail : maisonlogiciellibre@etsmtl.net

Ici nous nous concentrons sur le site en lui même et non sur les données qu'il entraine.

PS: Si tu rencontre des difficultés avec la manipulation, n'hésite pas à me revenir à ce sujet.
