### ISSUE TITLE
Associer un mentor à une mission sans créer de compte

### ISSUE THREAD

**Issue by aviau** [MaisonLogicielLibre/Website#706]
J'aimerais mettre un nom de mentor pour un projet, sans que celui ci aie un compte.

Peut-être qu'on pourais mettre son nom et son courriel?

__C'est lourd__ pour les organisations de demander à tout leur mentors de se créer un compte sur le site de ML2. Généralement, il va avoir un ''Contact ML2'' qui va se charger de créer les projets sur le site de ML2 et ensuite de référer au mentor. Mais cette personne n'est pas vraiment le mentor.

Comme on peux voir:

- Pascal n'est pas le mentor pour le projet de santropol, mais il s'est mis mentor parce que Emannuel n'avait pas de compte. ([ici](https://maisonlogiciellibre.org/projects/view/24))

-  Irmgard Van der Krift n'est probablement pas le mentor pour Chrome, mais elle s'est mise mentor parce que le vrais mentor n'avais pas de compte ([ici](https://maisonlogiciellibre.org/missions/view/13))

**Comment by RignonNoel** [comment]
C'est effectivement un point à revoir.

Il pourrait être intéressant de :
 - renommer "mentor" en "contact"
 - créer un/des champs mentors
  - Le nom
  - Le rôle (facultatif)
  - Un email public (facultatif)
  - Un numéro de téléphone (facultatif)

Je vais mettre l'idée dans les choses à discuter. Si tu a toi même une idée précise n'hésite pas a nous la partager.

**Comment by RignonNoel** [comment]
Maison du logiciel libre a besoin d’avoir un compte comme mentor pour plusieurs raisons:

- C’est lui qui s’occupe d’accepter/refuser les candidatures
- C’est lui qui doit remplir les testimoniaux (fonctionnalité future)
- C’est un moyen facile pour avoir des informations de contact

Ta demande pose plusieurs problèmes:

- Le mentor ne pourrait pas écrire lui-même les testimoniaux
- Le mentor ne serait pas la personne responsable des candidatures (alors que c’est lui l’expert)

Pour le moment, je ne peux donc te proposer que ceci:

1 - Inscrire le réel mentor sur le site et le définir comme mentor
2 - Vous accorder en interne et mettre au besoin des informations de contact dans la description

La solution n°1 étant de fait la plus cohérente avec notre plateforme.
