### ISSUE TITLE
Linux ne s'écrit pas en majuscules

### ISSUE THREAD

**Issue by aviau** [MaisonLogicielLibre/Website#709]
Typo dans le nom de SFL.

![screenshot from 2015-12-11 15-18-56](https://cloud.githubusercontent.com/assets/2706882/11754653/8ed28432-a01a-11e5-846e-2df36f95a542.png)

**Comment by RignonNoel** [comment]
Effectivement, l'erreur est venu de leurs logo où 'Linux' est marqué en majuscule.
Nous allons corriger cela.

**Comment by RignonNoel** [comment]
Merci d'avoir relevé l'erreur!
N'hésite pas si tu relève d'autre erreur ou amélioration ;)
