### ISSUE TITLE
Page d'org - ne pas afficher les projets archivés

### ISSUE THREAD

**Issue by aviau** [MaisonLogicielLibre/Website#711]
En fesant des manipulations, jai créer un projet de même nom, et je l'ai archivé. Parcontre, il apparait toujours dans ma liste de projets. C'est un peu dérangeant, je me trompes une fois sur 2.

Peut-être afficher les projets archivés dans une autre liste? Ou les cacher complètement.

![screenshot from 2015-12-11 15-28-19](https://cloud.githubusercontent.com/assets/2706882/11754818/e07f0eb2-a01b-11e5-8952-02a8800c384f.png)

**Comment by RignonNoel** [comment]
Effectivement, tu devrais disposer d'un badge à côté de celui archivé.
Le lien devrais de plus être innactif si tu n'en ai pas le propriétaire.

**Comment by aviau** [comment]
![screenshot from 2015-12-11 15-37-35](https://cloud.githubusercontent.com/assets/2706882/11754968/20cd2aac-a01d-11e5-80e1-cfffc63bb81f.png)

Ici tu peux voir que mon projet (qui est archivé), est en attente de validation. Innutile de valider un projet archivé, p-e qu'il faudrait canceler le processus de validation aussi?

**Comment by RignonNoel** [comment]
Je vais créer un nouveau ticket a ce sujet. Concernant celui-ci, il est résolu et en production.
