### ISSUE TITLE
Frontpage - bannière ne se resize pas

### ISSUE THREAD

**Issue by aviau** [MaisonLogicielLibre/Website#712]
Ca serait cool si la bannière sur la front-page s'adaptais à la page.

Elle est jamais de la bonne grandeur, sauf si t'est fullscreen (coupé sur les côtés):

![screenshot from 2015-12-11 15-34-13](https://cloud.githubusercontent.com/assets/2706882/11754944/e8f32b4a-a01c-11e5-9508-e38c9daa3ed3.png)

**Comment by RignonNoel** [comment]
L'image est coupé sur les côté car on ne veux pas la déformer pour garder en lisibilité.

Toute les vrai résolution (plein écran) sont supporté, 

Est-ce que chez toi l'image est coupé lorsque tu est en plein écran?

**Comment by aviau** [comment]
> Est-ce que chez toi l'image est coupé lorsque tu est en plein écran?

Non, mais j'ai rarement seulement une fenêtre d'ouverte à la fois. Donc j'accorde rarement fullscreen à une page web.

**Comment by RignonNoel** [comment]
Je comprend ta demande, mais je ne peux malheuresement rien pour toi concernant cette fonctionnalité.

Je vais relancé le sujet en discussion lorsque possible, mais pour le moment la fonctionnalité fonctionne.

Si tu as une idée de display plus efficace je t'invite a nous la proposer en PR. Peut-être que celle-ci sera accepté.
