### ISSUE TITLE
page user - ne peut pas cliquer sur un projet en attente de validation

### ISSUE THREAD

**Issue by aviau** [MaisonLogicielLibre/Website#713]
Je ne peut pas cliquer sur DebSources :(

Je doit passer par projets -> Debsources

![screenshot from 2015-12-11 15-44-13](https://cloud.githubusercontent.com/assets/2706882/11755118/208f0258-a01e-11e5-9589-05f2849cc708.png)

**Comment by RignonNoel** [comment]
Effectivement, nous allons corriger cela.
