### ISSUE TITLE
postulation déjà accepté - bouton approuver toujours présent

### ISSUE THREAD

**Issue by aviau** [MaisonLogicielLibre/Website#714]
J'ai déjà approuvé la posutlation, mais le bouton est toujours présent dans les détails de l'application.

D'ailleurs, le bouton est mal présenté. Si le bouton approuve la posutlation, le texte devrait être "Approuver", et non "Approuvé".

![screenshot from 2015-12-11 15-47-10](https://cloud.githubusercontent.com/assets/2706882/11755183/8101b036-a01e-11e5-9cbc-7d2a358442a3.png)

**Comment by RignonNoel** [comment]
Effectivement, je passe le ticket en hotfix.
