### ISSUE TITLE
automatiquement inscrit aux courriels promotionels

### ISSUE THREAD

**Issue by aviau** [MaisonLogicielLibre/Website#715]
Je suis inscrit, mais jai rien accepté!

![screenshot from 2015-12-11 15-54-41](https://cloud.githubusercontent.com/assets/2706882/11755321/8a4b3008-a01f-11e5-8537-9a2606aebbaa.png)

Deux problèmes,

- On est forcé de s'incrire (pas de checkbox à l'inscirption)
- On est inscrit par défaut (illégal au Canada) 

[La loi dit](http://www.crtc.gc.ca/eng/com500/faq500.htm):
> The manner in which you request express consent cannot presume consent on the part of the end-user. Silence or inaction on the part of the end-user also cannot be construed as providing express consent. For example, a pre-checked box cannot be used, as it assumes consent.

**Comment by RignonNoel** [comment]
Je vais rajouter aux points à discuter. Merci.

**Comment by RignonNoel** [comment]
Je ne sais pas si nous sommes concerné par ton article de loi puisque nous n'envoyons aucun message d'ordre commercial. Je vais cependant faire remonté l'information.

> A key question to ask yourself is the following: Is the message I am sending a CEM? Is one of the purposes to encourage the recipient to participate in commercial activity?

> When determining whether a purpose is to encourage participation in commercial activity, some parts of the message to look at are:

>     the content of the message
    any hyperlinks in the message to website content or a database, and
    contact information in the message.

> These parts of the message are not determinative. For example, the simple inclusion of a logo, a hyperlink or contact information in an email signature does not necessarily make an email a CEM. Conversly, a tagline in a message that promotes a product or service that encourages the recipient to purchase that product or service would make the message a CEM.

> Some examples of CEMs include:

>     offers to purchase, sell, barter or lease a product, goods, a service, land or an interest or right in land;
    offers to provide a business, investment or gaming opportunity;
    promoting a person, including the public image of a person, as being a person who does anything referred to above, or who intends to do so.

**Comment by fxleblanc** [comment]
Une fois qu'on aura un blogue, il sera plus simple d'intérgrer la mailing list, je transfère le problème dans le repository du Blog. 

https://github.com/MaisonLogicielLibre/Blog/issues/3
