### ISSUE TITLE
Type of mission seeked

### ISSUE THREAD

**Issue by RaphaelStArnaud** [MaisonLogicielLibre/Website#729]
Add the types of missions a student seek on its profile

### New users_type_missions table
- user_id -> The user
- type_mission_id -> Type of mission seeked

### New logic in the backend
- When a mission registered with the seeked type is created, the user is notified of the created mission

**Comment by fxleblanc** [comment]
@RaphaelStArnaud , what you are saying is that we need to show missions that may correspond to his list of competences or his interests for example?

**Comment by fxleblanc** [comment]
@RaphaelStArnaud we could reuse the skill list from the user model. However, we would need to have a similar list in the missions model. What is your approach on this subject?

**Comment by RignonNoel** [comment]
A skill list is not a type list.
Here we want know if the student want to be a capstone, an intern or just a volunter.

But the skill list is a good enhancement of this task

**Comment by fxleblanc** [comment]
Transfering feature to #867

**Comment by RignonNoel** [comment]
Yes you can transfert. But add this point to the new issue, for the moment its two tasks.

**Comment by fxleblanc** [comment]
What point are you refering to? Since these two features require model changes, I think it's a good idea to make seperate task for them. Is there anything I am missing?

**Comment by RignonNoel** [comment]
J'ai peur de mal me faire comprendre.

Tu vient de dite que tu transférer cette issue sur une autre, ce qui sous entend que celle ci n'existe plus, ou sinon ce n'est pas un transfert mais juste un lien.

Si tu la transfert, pense à préciser dans l'autre issue le fait qu'il faut ajouter un choix de type de mission pour les utilisateur sur leurs profil, car sinon on va perdre ce besoin dans les méandres des issues fermé.

**Comment by fxleblanc** [comment]
Ok je comprends ton point. Cette issue n'est pas fermée. La fonctionnalité que tu as précisée dans l'issue courante est transférée par contre pour la séparation. Quand je disais transfer, je parlais de la nouvelle fonctionnalité et non pas la courante. Désolé pour le choix de mots.

**Comment by fxleblanc** [comment]
@RignonNoel, dans quel jour de la semaine serait-il le plus intéressant d'envoyer le courriel.
