### ISSUE TITLE
Intro to Git

### ISSUE THREAD

**Issue by luctrudeau** [MaisonLogicielLibre/Website#792]
Short (1hr) workshop (over lunch)

Game based workshop using http://pcottle.github.io/learnGitBranching/

Content covered:
- Clone (level remote1)
- Pull (level remote4)
- Push (level remote6)
- Commit (level intro1)
- Branch (level intro2)
- Merge (level intro3)
- _Rebase_ (level intro4)

**Comment by luctrudeau** [comment]
Game based workshop using http://pcottle.github.io/learnGitBranching/

Content covered:
  * Clone (level remote1)
  * Pull (level remote4)
  * Push (level remote6)
  * Commit (level intro1)
  * Branch (level intro2)
  * Merge (level intro3)
  * _Rebase_ (level intro4)

**Comment by RignonNoel** [comment]
it would be interesting to talk about workflow with git (git flow)

or just introduce a documentation on this subject for students to continue after the workshop

**Comment by luctrudeau** [comment]
We can look into adding this to a more advanced workshop
