### ISSUE TITLE
DataTable Warning

### ISSUE THREAD

**Issue by luctrudeau** [MaisonLogicielLibre/Website#793]
Error when clicking on wiki link for organisation.

DataTables warning: table id = projects - Ajax error.

**Comment by luctrudeau** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://maisonlogiciellibre.org/projects?draw=4&columns%5B0%5D%5Bdata%5D=id…art=0&length=50&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1452714262042

**Comment by fxleblanc** [comment]
As a temporary solution, we could deactivate to option to filter all together. If we all agree on that solution, I'll make a seperate issue.

**Comment by fxleblanc** [comment]
Temporary fix with #891. Closing for now.
