### ISSUE TITLE
Official social network account urls and calendar for ML2

### ISSUE THREAD

**Issue by fxleblanc** [MaisonLogicielLibre/Website#810]
- Google Calendar
- Facebook
- Twitter
- Meetup

**Comment by appliedrd** [comment]
https://twitter.com/ML2_ETS
meetup org created. need to setup 1st meetup (and pay!)
facebook is MT
https://calendar.google.com/calendar/embed?src=etsmtl.net_iu7pki0ov8q0i7d5rkhckhqu48%40group.calendar.google.com&ctz=America/Toronto

**Comment by fxleblanc** [comment]
Meetup account transfered in #815

**Comment by fxleblanc** [comment]
Facebook page in #752

**Comment by luctrudeau** [comment]
I added myself to the calendar!
