### ISSUE TITLE
Show project and mission archived

### ISSUE THREAD

**Issue by RignonNoel** [MaisonLogicielLibre/Website#834]
We need to show project archived to show success of ML²

(Add a columns in index page with a select on active by default?)

**Comment by fxleblanc** [comment]
Maybe this will get annoying for people to always deactivate it. Maybe a better option would be to include applications that have been accepted in the weekly mail(#729). This would show the progression without clutering the main interface.

**Comment by fxleblanc** [comment]
transfered to #895
