### ISSUE TITLE
update.md

### ISSUE THREAD

**Issue by fxleblanc** [MaisonLogicielLibre/Website#841]
What are we supposed to see in update.md?

**Comment by RignonNoel** [comment]
On doit y trouver les étapes de mise à faire durant la migration du code sur le serveur.

Tu as des informations sur le contributing.MD à ce sujet

**Comment by fxleblanc** [comment]
À part lancer le script, est-ce qu'il y a quelque chose de spécial?

**Comment by RignonNoel** [comment]
C'est pas un script c'est juste une liste de rappel des choses à faire pour la prochaine mise en prod.

**Comment by fxleblanc** [comment]
Par script je veux dire que pour moi la mise en prod est tout simplement d'aller sur le serveur et de lancer le script. Quand tu parles d'une liste de choses à faire, de quoi parles-tu plus précisement?
