### ISSUE TITLE
[Object object] in mission type

### ISSUE THREAD

**Issue by luctrudeau** [MaisonLogicielLibre/Website#846]
My Daala mission as now been split into 4 missions of types: Maitrise, [object Object], projet de fin d'études, professeur

**Comment by fxleblanc** [comment]
Is it supposed to be:
- Bénévole
- Maîtrise
- Projet de fin d'étude
- Professeur

**Comment by fxleblanc** [comment]
In release 1.3, we seperated the missions for each type. Are the types in the previous comment accurate?
