### ISSUE TITLE
Official ETS website for Graduate projects

### ISSUE THREAD

**Issue by luctrudeau** [MaisonLogicielLibre/Website#860]
Prof already use this website (plain HTML, in a closed source tool) to put up projects offerings.

http://www.etsmtl.ca/Etudiants-actuels/Cycles-sup/Liste-des-fiches#GenieLogiciel

We can do better. One idea is a RESTful interface that produces an HTML table of a professors projects in ML2.

**Comment by fxleblanc** [comment]
Ties in with #813
