### ISSUE TITLE
"In the media" section

### ISSUE THREAD

**Issue by luctrudeau** [MaisonLogicielLibre/Website#918]
ML2 is present in different news paper and magazine, maybe we should track this and showcase it

This is what I have so far: 
la presse:
http://affaires.lapresse.ca/portfolio/formation-des-ingenieurs/201601/14/01-4939705-genie-informatique-et-logiciel-petites-revolutions-dans-les-formations.php

Revue Plan [p.10]
https://asp-indus.secure-zone.net/v2/index.jsp?id=458/488/4357&lng=fr

Canoe:
http://fr.canoe.ca/techno/materiel/archives/2015/12/20151202-171132.html

DirectionInformatique:
http://www.directioninformatique.com/maison-ets-et-google-du-logiciel-libre/39365

France Diplomatie:
http://www.diplomatie.gouv.fr/fr/politique-etrangere-de-la-france/diplomatie-scientifique/veille-scientifique-et-technologique/canada/article/inauguration-de-la-maison-du-logiciel-libre-a-l-ecole-de-technologie-superieure?xtor=RSS-4

Reddit: 
https://www.reddit.com/r/montreal/comments/3vawpv/l%C3%A9ts_ouvre_la_maison_du_logiciel_libre_un_concept/

LienMultimedia.com:
http://www.lienmultimedia.com/spip.php?article51399

Substance:
http://substance-en.etsmtl.ca/creation-of-maison-du-logiciel-libre-at-ets/

**Comment by fxleblanc** [comment]
Maybe inserting these articles in the news section would be a good start.

**Comment by RignonNoel** [comment]
Yes, a little description and a link for all articles seems to be à good idea.
